# VULNERABLE: Kubernetes manifests with intentionally insecure configurations
# DO NOT APPLY TO REAL CLOUD - FOR EDUCATIONAL PURPOSES ONLY

apiVersion: v1
kind: Namespace
metadata:
  name: vuln-lab
  # VULNERABLE: No security policies applied

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vuln-lab-sa
  namespace: vuln-lab
  # VULNERABLE: No RBAC restrictions

---
# VULNERABLE: Overly permissive ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vuln-lab-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
  # VULNERABLE: Full cluster access

---
# VULNERABLE: Binding service account to overly permissive role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vuln-lab-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vuln-lab-cluster-role
subjects:
- kind: ServiceAccount
  name: vuln-lab-sa
  namespace: vuln-lab

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vuln-lab-config
  namespace: vuln-lab
data:
  # VULNERABLE: Hardcoded secrets in ConfigMap
  database_url: "sqlite:///fake_lab.db"
  api_key: "FAKE_1234567890abcdef"
  secret_token: "FAKE_vulnerable_token_for_lab_only"
  admin_password: "FAKE_admin123"

---
apiVersion: v1
kind: Secret
metadata:
  name: vuln-lab-secret
  namespace: vuln-lab
type: Opaque
data:
  # VULNERABLE: Base64 encoded secrets (easily decoded)
  database_password: RkFLRV9wYXNzd29yZDEyMw==
  jwt_secret: RkFLRV9qd3Rfc2VjcmV0X2tleV8xMjM0NQ==
  encryption_key: RkFLRV9lbmNyeXB0aW9uX2tleV8xMjM0NTY3ODkwMTIzNDU2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-lab-app
  namespace: vuln-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-lab-app
  template:
    metadata:
      labels:
        app: vuln-lab-app
    spec:
      # VULNERABLE: Running as root
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      serviceAccountName: vuln-lab-sa
      containers:
      - name: vuln-lab-app
        image: vuln-lab-app:latest
        # VULNERABLE: Running with privileged access
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add:
            - ALL
        ports:
        - containerPort: 8000
        - containerPort: 3000
        env:
        # VULNERABLE: Exposing secrets as environment variables
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: vuln-lab-config
              key: database_url
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: vuln-lab-config
              key: api_key
        - name: SECRET_TOKEN
          valueFrom:
            configMapKeyRef:
              name: vuln-lab-config
              key: secret_token
        - name: ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: vuln-lab-config
              key: admin_password
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vuln-lab-secret
              key: database_password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: vuln-lab-secret
              key: jwt_secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: vuln-lab-secret
              key: encryption_key
        # VULNERABLE: No resource limits
        resources: {}
        # VULNERABLE: Mounting host paths
        volumeMounts:
        - name: host-data
          mountPath: /app/data
        - name: host-logs
          mountPath: /app/logs
        - name: host-config
          mountPath: /app/config
      volumes:
      # VULNERABLE: Host path mounts
      - name: host-data
        hostPath:
          path: /var/lib/vuln-lab/data
          type: DirectoryOrCreate
      - name: host-logs
        hostPath:
          path: /var/lib/vuln-lab/logs
          type: DirectoryOrCreate
      - name: host-config
        hostPath:
          path: /etc/vuln-lab/config
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: vuln-lab-service
  namespace: vuln-lab
spec:
  selector:
    app: vuln-lab-app
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: dashboard
    port: 3000
    targetPort: 3000
    protocol: TCP
  # VULNERABLE: No network policies
  type: ClusterIP

---
# VULNERABLE: NetworkPolicy allowing all traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vuln-lab-network-policy
  namespace: vuln-lab
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
  # VULNERABLE: Allows all ingress and egress traffic

---
# VULNERABLE: PodSecurityPolicy with overly permissive settings
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vuln-lab-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  hostNetwork: true
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  # VULNERABLE: Allows privileged containers and host access
